from Settings.defaultSettings import *


##Create a unique secret key for the project
try:
    from Settings.secret_key import *
except ImportError:
    from django.utils.crypto import get_random_string
    SETTINGS_DIR=os.path.abspath(os.path.dirname(__file__))
    chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'
    secret_key = get_random_string(50, chars)

    secretfile = open(SETTINGS_DIR+"/secret_key.py", 'w')
    secretfile.write("SECRET_KEY = \'"+secret_key+"\'\n")
    secretfile.close()
    from Settings.secret_key import *

##################
#Production enviroment settings overrides. You can override Settings/defaultSettings.py settings from here.
#If you're a developer, you want to be editing the defaultSettings file instead.
#Only edit this file if you're deploying it. And make sure it's not being updated by typing "git update-index --assume-unchanged Settings/settings.py"
##################

#This file was autogenerated by ansible on {{ ansible_date_time.date }}
{# Unless you can see this line, in which case you're editing the template used to generate this file #}

ADMINS = [
    ('admin','admin+errors@{{domain}}'),
{% for name, adminDomain in admins %}
    ('{{name}}', '{{admin}}+errors+{{domain}}@{{adminDomain}}'),
{% endfor %}
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': '{{dbName}}',
        'USER': '{{dbUser}}',
        'PASSWORD': '{{dbPasswordCommand.stdout}}',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

DEBUG = '{{debug | default('False')}}'
ALLOWED_HOSTS += ["{{}}"]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = '{{email_host}}'
EMAIL_PORT = '{{email_port}}'
EMAIL_HOST_USER = '{{email_host_user}}'
EMAIL_HOST_PASSWORD = '{{email_host_password}}'
DEFAULT_FROM_EMAIL = "{{default_from_email | default(email_user+'@'+email_host)}}"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

EMAIL_USE_TLS = '{{email_use_tls | default('False')}}'
EMAIL_USE_SSL = '{{email_use_ssl | default('False')}}'

INSTALLED_APPS += {{ apps | default("[ ]")}}
STATIC_ROOT = '/home/{{user}}/{{domain}}-static/'
MEDIA_ROOT = '/home/{{user}}/{{domain}}-media/'
